<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>RKmission</AssemblyName>
    <RootNamespace>RKmission</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AOSharpSDK" Version="1.0.106" />
    <PackageReference Include="AOSharpSDK.Nav" Version="1.0.5" />
    <PackageReference Include="AOSharpSDK.SharpNav" Version="1.0.44" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>
